// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQUp_8KqO3ytknot6Ygpcy_uqRgWwuZKY',
    appId: '1:584004825007:web:3a7a4e4add72037f30495a',
    messagingSenderId: '584004825007',
    projectId: 'todolist-9d1e6',
    authDomain: 'todolist-9d1e6.firebaseapp.com',
    storageBucket: 'todolist-9d1e6.firebasestorage.app',
    measurementId: 'G-9ZF9PX2V7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2k_TkHOX6x5Yg3Ak9n4SforMwMpc62bM',
    appId: '1:584004825007:android:77af923782db13df30495a',
    messagingSenderId: '584004825007',
    projectId: 'todolist-9d1e6',
    storageBucket: 'todolist-9d1e6.firebasestorage.app',
  );
}
